apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngrok
  labels:
    app: ngrok
spec:
  selector:
    matchLabels:
      app: ngrok
  replicas: 1
  template:
    metadata:
      labels:
        app: ngrok
    spec:
      containers:
        - name: ngrok
          image: ngrok:3
          args: ['http', 'atlantis:80']
          ports:
            - containerPort: 4040
