apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml

images:
  - name: ngrok
    newName: ngrok/ngrok
    newTag: '3'
  - name: kubefirst/git-helper
    newName: kubefirst/git-helper
    newTag: 'v0.1.0'

generatorOptions:
  disableNameSuffixHash: true
