apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: ngrok
    newName: ngrok/ngrok
    newTag: '3'

generatorOptions:
  disableNameSuffixHash: true
