apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: cwft-docker
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  templates:
    - name: login-build-push
      inputs:
        artifacts:
          - name: repo-source
            path: /src
        parameters:
          - name: appName
            value: '{{workflow.parameters.appName}}'
          - name: containerRegistryURL
            value: '{{workflow.parameters.containerRegistryURL}}'
          - name: dockerFilePath
            value: '{{workflow.parameters.dockerFilePath}}'
      container:
        image: kubefirst/chubbo:0.2
        command: ['bash', '-c']
        workingDir: '/src/{{inputs.parameters.appName}}'
        args:
          - until docker ps; do sleep 3; done;
            docker login registry.gitlab.com --username ${username} --password ${password};
            echo building {{workflow.parameters.containerRegistryURL}};
            docker build -t {{workflow.parameters.containerRegistryURL}} -f {{inputs.parameters.dockerFilePath}} .;
            docker push {{workflow.parameters.containerRegistryURL}};
        env:
          - name: DOCKER_HOST
            value: 'tcp://localhost:2375'
        envFrom:
          - secretRef:
              name: ci-secrets
      sidecars:
        - name: dind
          image: docker:19.03.13-dind
          env:
            - name: DOCKER_TLS_CERTDIR
              value: ''
          securityContext:
            privileged: true
          mirrorVolumeMounts: true
