apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: cwft-buildkit
spec:
  entrypoint: build-push
  templates:
    - name: build-push
      inputs:
        parameters:
          - name: appRepoUrl
            value: https://gitlab.com/{{workflow.parameters.gitOwner}}/{{workflow.parameters.appName}}
        artifacts:
          - name: app-source
            path: '/work/{{workflow.parameters.appName}}'
            git:
              repo: '{{inputs.parameters.appRepoUrl}}'
              branch: '{{workflow.parameters.branch}}'
              singleBranch: true
              usernameSecret:
                name: ci-secrets
                key: username
              passwordSecret:
                name: ci-secrets
                key: password
          - name: docker-config
            path: '/tmp/config.json'
      # Mount the configuration so we can push the image.
      # This should create the /.docker/config.json file.
      # volumes:
      #   - name: docker-config
      #     secret:
      #       secretName: docker-config
      container:
        image: moby/buildkit:v0.11.3-rootless
        volumeMounts:
          - name: work
            mountPath: /work
        workingDir: /work/{{workflow.parameters.appName}}
        env:
          - name: BUILDKITD_FLAGS
            value: --oci-worker-no-process-sandbox
          - name: DOCKER_CONFIG
            value: /tmp
        command:
          - buildctl-daemonless.sh
        args:
          - build
          - --frontend
          - dockerfile.v0
          - --local
          - context=.
          - --local
          - dockerfile=build
          - --output
          - type=image,name={{workflow.parameters.containerRegistryURL}},push=true
    - name: create-docker-config
      inputs:
        parameters:
          - name: docker-config
            value: '{{workflow.parameters.gitlabRegistryAuth}}'
      container:
        image: kubefirst/chubbo:0.2
        command: ['bash', '-c']
        args:
          ['echo {{inputs.parameters.docker-config}} | tee /tmp/config.json']
      outputs:
        artifacts:
          - name: docker-config
            path: /tmp/config.json
